env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-restricted-syntax: ['off', 'ForOfStatement']
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  implicit-arrow-linebreak: ['off']
  object-curly-newline: ['off']
  no-new: 0
  object-shorthand: 0
